### PR TITLE
Add Flask app's static_folder support.

### PR DESCRIPTION
**Pull request by arikai**
Flask-less uses relative paths by default. Use of static_folder parameter from Flask app would be more reasonable.

### CODE REVIEW

**Comment by mrf345** [comment]
@arikai Thanks for the improvements and corrections 👍

**Comment by arikai** [comment]
@mrf345 Do you mind updating PyPI package?

**Comment by mrf345** [comment]
@arikai just did 0.6, forgot it had a package😅

**Comment by arikai** [comment]
@mrf345 Thank you!
(And don't forget to close PR)

**Pull request merged**
